services:
  - type: web
    name: smart-tourist-safety-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health

  - type: web
    name: smart-tourist-safety-frontend
    env: static
    buildCommand: cd client && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./client/build
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
